from django.urls import path

from . import views

urlpatterns = [
    path("", views.root),
    path("api", views.root),
    path("api/", views.root),
    path("api/health", views.health),
    path("api/healthz", views.health),
    path("api/auth/register", views.register),
    path("api/auth/login", views.login),
    path("api/auth/perfil", views.profile),
    path("api/auth/verificar/<str:token>", views.verify_email),
    path("api/auth/forgot-password", views.forgot_password),
    path("api/auth/reset-password", views.reset_password),
    path("api/categorias", views.CategoryCollection.as_view()),
    path("api/categorias/<uuid:pk>", views.CategoryDetail.as_view()),
    path("api/marcas", views.BrandCollection.as_view()),
    path("api/marcas/<uuid:pk>", views.BrandDetail.as_view()),
    path("api/modelos-moto", views.ModelCollection.as_view()),
    path("api/modelos-moto/<uuid:pk>", views.ModelDetail.as_view()),
    path("api/motos", views.MotorcycleCollection.as_view()),
    path("api/motos/<uuid:pk>", views.MotorcycleDetail.as_view()),
    path("api/roles", views.RoleCollection.as_view()),
    path("api/roles/<uuid:pk>", views.RoleDetail.as_view()),
    path("api/tiendas", views.StoreCollection.as_view()),
    path("api/tiendas/<uuid:pk>", views.StoreDetail.as_view()),
    path("api/usuarios", views.UserCollection.as_view()),
    path("api/usuarios/<uuid:pk>", views.UserDetail.as_view()),
    path("api/modelos-3d", views.Model3DCollection.as_view()),
    path("api/modelos-3d/accesorio/<uuid:id_accesorio>", views.Model3DByAccessory.as_view()),
    path("api/modelos-3d/<uuid:pk>", views.Model3DDetail.as_view()),
    path("api/accesorios", views.AccessoryCollection.as_view()),
    path("api/accesorios/<uuid:pk>", views.AccessoryDetail.as_view()),
    path("api/compatibilidad/modelo/<uuid:id_modelo_moto>", views.AccessoriesByModel.as_view()),
    path("api/compatibilidad/accesorio/<uuid:id_accesorio>", views.ModelsByAccessory.as_view()),
    path("api/compatibilidad", views.CompatibilityCollection.as_view()),
    path("api/compatibilidad/<uuid:pk>", views.CompatibilityDetail.as_view()),
    path("api/inventario", views.InventoryCollection.as_view()),
    path("api/inventario/movimiento", views.InventoryMovement.as_view()),
    path("api/inventario/<uuid:pk>", views.InventoryDetail.as_view()),
    path("api/cotizaciones", views.QuoteCollection.as_view()),
    path("api/cotizaciones/<uuid:pk>", views.QuoteDetail.as_view()),
    path("api/cotizaciones/<uuid:pk>/estado", views.QuoteStatus.as_view()),
]
